name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if a feature request already exists.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Suggested API (optional)
      description: If you have ideas about how this feature should be implemented, share them here.
      placeholder: |
        ```vue
        <VMap :options="mapOptions">
          <VLayerNewFeature :some-prop="value" />
        </VMap>
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package should this feature be added to?
      options:
        - '@geoql/v-maplibre'
        - 'mapcn-vue'
        - Both
        - New package
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: importance
    attributes:
      label: How important is this feature?
      options:
        - Nice to have
        - Important - would significantly improve my workflow
        - Critical - blocking my project
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Are you willing to contribute?
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false
