<script setup lang="ts">
  import { VMap, VControlNavigation, VControlScale } from '@geoql/v-maplibre';
  import { VLayer3DTiles } from '@geoql/v-maplibre/3d-tiles';

  usePageGeo({
    title: '3D Splat Scene - mapcn-vue Examples',
    description:
      'Stream a KHR_gaussian_splatting SPZ splat tileset rendered by three.js on a MapLibre basemap.',
  });

  defineOgImage('MapcnDoc', {
    title: '3D Splat Scene',
    description:
      'Stream a KHR_gaussian_splatting SPZ splat tileset rendered by three.js on a MapLibre basemap.',
    category: '3D Splats & Tiles',
  });

  const { mapStyle } = useMapStyle();
  const mapId = useId();
  const config = useRuntimeConfig();
  const assetsBase = config.public.r2AssetsBase;

  // geolith-generated tileset (geolith/geolith#17): SPZ splat tiles with
  // KHR_gaussian_splatting — an outward-facing CC0 capture at true metric
  // scale (steam-studio.jp), self-anchored via its ECEF root transform near
  // Tokyo Tower. Pinned to altitude 0 so the content sits on the flat
  // basemap: without a DEM the map's ground plane is 0 m.
  const tilesetUrl = `${assetsBase}/splat/cactus/tileset.json`;

  const mapOptions = computed(() => ({
    container: `3d-buildings-example-${mapId}`,
    style: mapStyle.value,
    center: [139.7454, 35.6586] as [number, number],
    zoom: 20.5,
    pitch: 60,
    bearing: -20,
    maxPitch: 85,
    maxZoom: 23,
    antialias: true,
  }));

  const loading = ref(true);

  const onLoadTileset = () => {
    loading.value = false;
  };

  const SCRIPT_END = '</' + 'script>';
  const SCRIPT_START = '<' + 'script setup lang="ts">';

  const codeExample = `${SCRIPT_START}
                import { VMap, VControlNavigation } from '@geoql/v-maplibre';
                import { VLayer3DTiles } from '@geoql/v-maplibre/3d-tiles';

                // Peers: pnpm add three 3d-tiles-renderer @sparkjsdev/spark \\
                //          3d-tiles-rendererjs-3dgs-plugin

                const mapOptions = {
                  style: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
                  center: [139.7454, 35.6586],
                  zoom: 20.5,
                  pitch: 60,
                  bearing: -20,
                  maxPitch: 85,
                  antialias: true,
                };

                // geolith gaussian splat tileset (SPZ + KHR_gaussian_splatting)
                const tilesetUrl =
                  'https://your-bucket.example.com/splat/cactus/tileset.json';
              ${SCRIPT_END}

              <template>
                <VMap :options="mapOptions" class="h-125 w-full">
                  <VControlNavigation position="top-right" />
                  <VLayer3DTiles
                    id="splat-tileset"
                    :url="tilesetUrl"
                    :error-target="8"
                    :altitude="0"
                    :rotation="[90, 0, 0]"
                    :fade="true"
                    :splats="true"
                    @load-tileset="onLoadTileset"
                  />
                </VMap>
              </template>`;
</script>

<template>
  <ComponentDemo
    title="3D Splat Scene"
    description="Stream a KHR_gaussian_splatting SPZ splat tileset rendered by three.js on a MapLibre basemap — LOD refinement and tile fade via NASA-AMMOS 3DTilesRendererJS. Tileset generated by the geolith pipeline."
    :code="codeExample"
    full-width
    class="h-full"
  >
    <div class="relative size-full min-w-0 overflow-hidden">
      <ClientOnly>
        <VMap :key="mapStyle" :options="mapOptions" class="size-full">
          <VControlNavigation position="top-right" />
          <VControlScale position="bottom-left" />
          <VLayer3DTiles
            id="splat-tileset"
            :url="tilesetUrl"
            :error-target="8"
            :altitude="0"
            :rotation="[90, 0, 0]"
            :fade="true"
            :splats="true"
            @load-tileset="onLoadTileset"
          />
        </VMap>
      </ClientOnly>
      <div
        v-if="loading"
        class="bg-background/80 absolute top-3 left-1/2 -translate-x-1/2 rounded-md border px-3 py-1.5 font-mono text-xs backdrop-blur"
      >
        Streaming tileset…
      </div>
    </div>
  </ComponentDemo>
</template>
