<script setup lang="ts">
  import { VMap, VControlNavigation, VControlScale } from '@geoql/v-maplibre';
  import { VLayer3DTiles } from '@geoql/v-maplibre/3d-tiles';

  usePageGeo({
    title: '3D Tiles Splat Layer - mapcn-vue Examples',
    description:
      'Stream an OGC 3D Tiles tileset with KHR_gaussian_splatting SPZ splat tiles on the map.',
  });

  defineOgImage('MapcnDoc', {
    title: '3D Tiles Splat Layer',
    description:
      'Stream an OGC 3D Tiles tileset with KHR_gaussian_splatting SPZ splat tiles on the map.',
    category: '3D Splats & Tiles',
  });

  const { mapStyle } = useMapStyle();
  const mapId = useId();
  const config = useRuntimeConfig();
  const assetsBase = config.public.r2AssetsBase;

  // geolith-generated tileset (geolith/geolith#15): SPZ splat tiles with
  // KHR_gaussian_splatting, self-anchored via its ECEF root transform near
  // the Belvedere Glacier at ~2250 m.
  const tilesetUrl = `${assetsBase}/splat/bonsai/tileset.json`;

  const mapOptions = computed(() => ({
    container: `tiles-3d-example-${mapId}`,
    style: mapStyle.value,
    center: [7.9797, 45.9756] as [number, number],
    zoom: 18.5,
    pitch: 60,
    bearing: -20,
    maxPitch: 85,
  }));

  const loading = ref(true);

  const onLoadTileset = () => {
    loading.value = false;
  };

  const SCRIPT_END = '</' + 'script>';
  const SCRIPT_START = '<' + 'script setup lang="ts">';

  const codeExample = `${SCRIPT_START}
                import { VMap, VControlNavigation } from '@geoql/v-maplibre';
                import { VLayer3DTiles } from '@geoql/v-maplibre/3d-tiles';

                // Peers: pnpm add three 3d-tiles-renderer @dvt3d/maplibre-three-plugin \\
                //          @sparkjsdev/spark 3d-tiles-rendererjs-3dgs-plugin

                const mapOptions = {
                  style: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
                  center: [7.9797, 45.9756],
                  zoom: 18.5,
                  pitch: 60,
                  maxPitch: 85,
                };
              ${SCRIPT_END}

              <template>
                <VMap :options="mapOptions" class="h-125 w-full">
                  <VControlNavigation position="top-right" />
                  <VLayer3DTiles
                    id="splat-tileset"
                    url="https://your-bucket.example.com/tileset.json"
                    :error-target="8"
                    :fade="true"
                    :splats="true"
                    @load-tileset="onLoadTileset"
                  />
                </VMap>
              </template>`;
</script>

<template>
  <ComponentDemo
    title="3D Tiles Splat Layer"
    description="Stream an OGC 3D Tiles tileset — mesh tiles and KHR_gaussian_splatting SPZ splat tiles — with unified LOD, tile fade, and automatic disposal via NASA-AMMOS 3DTilesRendererJS. Tileset generated by the geolith pipeline."
    :code="codeExample"
    full-width
    class="h-full"
  >
    <div class="relative size-full min-w-0 overflow-hidden">
      <ClientOnly>
        <VMap :key="mapStyle" :options="mapOptions" class="size-full">
          <VControlNavigation position="top-right" />
          <VControlScale position="bottom-left" />
          <VLayer3DTiles
            id="splat-tileset"
            :url="tilesetUrl"
            :error-target="8"
            :altitude="0"
            :fade="true"
            :splats="true"
            @load-tileset="onLoadTileset"
          />
        </VMap>
      </ClientOnly>
      <div
        v-if="loading"
        class="bg-background/80 absolute top-3 left-1/2 -translate-x-1/2 rounded-md border px-3 py-1.5 font-mono text-xs backdrop-blur"
      >
        Streaming tileset…
      </div>
    </div>
  </ComponentDemo>
</template>
